//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Blogger.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogTravelEntities1 : DbContext
    {
        public BlogTravelEntities1()
            : base("name=BlogTravelEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<asia> asias { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<menu> menus { get; set; }
        public virtual DbSet<CountryEuru> CountryEurus { get; set; }
        public virtual DbSet<EUR> EURs { get; set; }
    }
}
